name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Maturin
        run: pip install maturin[patchelf]

      - name: Build wheels
        run: maturin build --release --out dist --strip

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-ci
          path: dist